env:
  CUDA_VISIBLE_DEVICES: "0,1,2,3,4,5,6,7"
  NCCL_DEBUG: INFO
  NCCL_BLOCKING_WAIT: "1"
  NCCL_P2P_DISABLE: "0"
  NCCL_SHM_DISABLE: "0"

project:
  name: ThermalFold

model:
  _target_:  ThermalFold.model.thermalfold_alphafold3.Alphafold3_thermal
  dim_atom_inputs: 3
  dim_template_feats: 8 #64
  dim_template_model: 8 #64
  atoms_per_window: 27
  dim_atom: 128 #128
  dim_atompair_inputs: 5
  dim_atompair: 16 #16
  dim_input_embedder_token: 192 #384
  dim_single: 192 #384
  dim_pairwise: 64 #128
  dim_token: 384 #768
  dim_additional_msa_feats: 2
  dim_additional_token_feats: 33
  num_atom_embeds: null
  num_atompair_embeds: null
  num_molecule_mods: 0
  #distance_bins: !!seq [2.0, 22.0, 64]
  #pae_bins: !!seq [0.5, 32.0, 64]
  #pde_bins: !!seq [0.5, 32.0, 64]
  ignore_index: -1
  num_dist_bins: 64
  num_plddt_bins: 50
  num_pae_bins: null
  num_pde_bins: null
  sigma_data: 16.0
  num_rollout_steps: 20
  diffusion_num_augmentations: 16 #48
  loss_confidence_weight: 0.1
  loss_distogram_weight: 0.5
  loss_diffusion_weight: 5.0
  loss_dssp_weight: 15
  input_embedder_kwargs:
    atom_transformer_blocks: 3
    atom_transformer_heads: 4
    atom_transformer_kwargs: {}
  confidence_head_kwargs:
    pairformer_depth: 4
  template_embedder_kwargs:
    pairformer_stack_depth: 2
    pairwise_block_kwargs: {}
    layerscale_output: true
  msa_module_kwargs:
    depth: 1 #4
    dim_msa: 8 #64
    outer_product_mean_dim_hidden: 32
    msa_pwa_dropout_row_prob: 0.15
    msa_pwa_heads: 8
    msa_pwa_dim_head: 32
    pairwise_block_kwargs: {}
    layerscale_output: true
  pairformer_stack:
    depth: 16 #24
    pair_bias_attn_dim_head: 32 #64
    pair_bias_attn_heads: 16
    dropout_row_prob: 0.25
    pairwise_block_kwargs: {}
  relative_position_encoding_kwargs:
    r_max: 32
    s_max: 2
  diffusion_module_kwargs:
    single_cond_kwargs:
      num_transitions: 2
      transition_expansion_factor: 2
    pairwise_cond_kwargs:
      num_transitions: 2
    atom_encoder_depth: 3
    atom_encoder_heads: 4
    token_transformer_depth: 12 #24
    token_transformer_heads: 12 #16
    atom_decoder_depth: 3
    atom_decoder_heads: 4
  edm_kwargs:
    sigma_min: 0.002
    sigma_max: 80
    rho: 7
    P_mean: -1.2
    P_std: 1.2
    S_churn: 80
    S_tmin: 0.05
    S_tmax: 50
    S_noise: 1.003
  plm_embeddings: null